### ISSUE TITLE
Refactor directory structure

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#274]
# Refactor Directory Structure

Title says it all.

# Task List
---

- [ ] ~~move all operators and pipelines from `/towhee/tests` to `/operators` and `/pipelines`~~
- [x] remove `emulated_pipeline` from `tests` directory.
- [x] move `/towhee/tests` to `/tests/unittests` and update relevant paths in test files.
- [ ] combine `/towhee/cnn_trainer` and `/towhee/trainer`, `data`.
- [x] combine `array`, and `dataframe`.
- [x] remove `data_source`.
- [x] ~~remove `utils` folder (so it does not become an outpost for random functions) and move existing files within, if possible~~ move `hub_tools.py` to separate `hub` folder and `handler_mixin.py` to engine

```
towhee [project]
  |- towhee [codebase]
  |- tests  # shares same directory tree as towhee [codebase]
  |- operators
  |- pipelines
  |- docs
  |- bootcamp
  |- setup.py
  |- README.md
  |- pylint.conf

towhee [codebase]
  |- engine
  |- models
    |- layers
    |- individual models
    |- utils
  |- trainer
    |- trainer.py  # abstract Trainer class
    |- train_args.py
    |- cnn_trainer.py
    |- transformer_trainer.py
    |- gan_trainer.py
  |- data
    |- dataset
      |- PytorchImageDataset.py
      |- PytorchVideoDataset.py
      |- TFImageDataset.py
    |- transforms
  |- cache
    |- hub
  |- common
    |- decorators
    |- mixins
  |- logger.py
  |- error.py
  |- type.py
```

**Comment by binbinlv** [comment]
@fzliu  for tests contents, I think it could be specified as the following. "UnitTest" part is for UT, and I will add all the functional tests part into "FunctionTest".  Thanks.

towhee [project]
  |- towhee [codebase]
  |- tests  # shares same directory tree as towhee [codebase]
      |- UnitTest
      |- FunctionTest
  |- operators
  |- pipelines
  |- docs
  |- bootcamp
  |- setup.py
  |- README.md
  |- pylint.conf

**Comment by fzliu** [comment]
@binbinlv This looks fine; we'll put our individual UTs under `towhee/tests/unittests` then.

**Comment by binbinlv** [comment]
@fzliu cool, thanks.
