### ISSUE TITLE
DAG implementation, testing, and integration with engine components

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#56]
# DAG Implementation Checklist

Based on the agreed upon architecture, the DAG will serve as a template for the way the engine moves data around in the pipeline. In essence, each engine component has a corresponding representation in the DAG:

* `GraphRepr`: A simple container for operators and dataframes. It does not explicitly hold any data regarding the dataflow between operators and dataframes.
* `OperatorRepr`: An operator abstraction. This will hold the operator function along with input and output dataframes and the iterators used for the respective dataframes.
* `DataframeRepr`: A dataframe representation. Essentially a collection of variable representations with no information about the operators which use or supply said dataframes.
* `VariableRepr`: A variable representation. Stores information about the individual variable, i.e. variable type (`ndarray`, `Image`, etc) without knowing which Dataframe it is a part of.

# Task List
---
#### Graph
- [ ] base implementation (attributes & helper functions)
- [ ] unit tests
- [ ] `from_yaml`
- [ ] `to_yaml`
- [ ] error checking: no cyclical loops

#### Operator
- [ ] base implementation (attributes & helper functions)
- [ ] unit tests
- [ ] error checking: no orphan operators
- [ ] error checking: all operators have both inputs and outputs

#### Dataframe
- [ ] base implementation (attributes & helper functions)
- [ ] unit tests
- [ ] `from_input_annotations`
- [ ] `from_output_annotations`
- [ ] error checking: no orphan dataframes
- [ ] error checking: all dataframes have input operators (except data sources)

#### Variable
- [ ] base implementation (attributes & helper functions)
- [ ] unit tests

#### Other Tests
- [ ] load yaml -> dump yaml identity checking tests
- [ ] engine can create pipeline using graph
