### ISSUE TITLE
Engine implementation, testing, and my-first-pipeline

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#58]
# Engine Implementation Checklist

The engine lies at Towhee's core, driving the dataflow, partitioning tasks to devices, and managing the overall state of the pipeline. When a user calls a `pipeline()` function, an `Pipeline` object and all associated contexts and device managers are created. Execution threads for each device is created through a `TaskExecutor`, and management of graph state is done through `GraphContext` and `OperatorContext` classes. Each `OperatorContext` is responsible for passively managing its own input iterators, while the `Scheduler` actively (periodically) asks each operator whether or not it has any tasks ready for processing. Each task is then assigned by the `Scheduler` to one of many `TaskExecutor` objects, resulting in parallel processing of simultaneous tasks.

This architecture allows a single pipeline to be run across one or many interconnected machines, each of which may have multiple devices.

# Task List
---

#### `GraphContext` and `OperatorContext` (~19 days)
- [x] graph state management
- [x] operator state management
- [x] data management and dataflow between operators
- [x] task acquisition, if input data is available
- [ ] unit tests

#### `Dataframe` and `Array` (~3 days)
- [x] integration with data source
- [x] `map` iterator (v0.1)
- [x] unit tests

#### `Task`, `TaskExecutor`, and `OperatorPool` (~9 days)
- [x] operator acquisition & release
- [x] task management
- [x] task execution
- [x] unit tests

#### `Scheduler` (~5 days)
- [x] looping FIFO scheduler implementation
- [x] basic integration tests with simple Operators
- [x] unit tests

#### `Pipeline` (~2 days)
- [x] `GraphContext` wrapper implementation
- [ ] unit tests

#### my-first-pipeline (~3 days)
- [ ] successful creation of pipeline using DAG
- [ ] successful processing with PyTorch models
